import { afterEach, describe, expect, test } from "bun:test";
import { mkdtemp, mkdir, rm } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { Database } from "bun:sqlite";
import { runMigration } from "./index";

const paths: string[] = [];
afterEach(async () => { await Promise.all(paths.splice(0).map((path) => rm(path, { recursive: true, force: true }))); });

async function fixture(options: { tool?: boolean; collision?: boolean; malformed?: boolean; partial?: boolean; attachment?: boolean; summary?: boolean; redactedThinking?: boolean; multiAttachment?: boolean } = {}) {
	const root = await mkdtemp(join(tmpdir(), "solar-v1-v2-")); paths.push(root); const sourceDb = join(root, "v1.db"); const assets = join(root, "assets"); await mkdir(assets);
	const db = new Database(sourceDb); db.exec("pragma foreign_keys=on; create table user (id text primary key, email text unique); create table folder (id text primary key, userId text not null, name text not null, createdAt text not null); create table tag (id text primary key, userId text not null, name text not null, createdAt text not null); create table conversation (id text primary key, userId text not null, title text not null, folderId text, provider text, endpointId text, modelId text, modelApi text, systemPrompt text, createdAt text not null, updatedAt text not null); create table conversation_tag (conversationId text, tagId text); create table message (id text primary key, conversationId text not null, role text not null, text text not null, parts text, status text not null, model text, inputTokens integer, outputTokens integer, createdAt text not null); create table generation_step (messageId text, sequence integer, data text, primary key(messageId, sequence)); create table attachment (id text primary key, userId text not null, messageId text, filename text not null, mimeType text not null, kind text not null, byteSize integer not null, storageKey text not null, createdAt text not null); create table conversation_context_state (conversationId text primary key, summary text);");
	const created = "2025-01-01T00:00:00.000Z"; db.query("insert into user values (?, ?)").run("u1", "one@example.test"); db.query("insert into folder values (?, ?, ?, ?)").run("f1", "u1", "Folder", created); db.query("insert into tag values (?, ?, ?, ?)").run("t1", "u1", "Tag", created); db.query("insert into conversation values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)").run("c1", "u1", "Chat", "f1", null, null, null, null, null, created, created); db.query("insert into conversation_tag values (?, ?)").run("c1", "t1");
	const assistant = JSON.stringify({ role: "assistant", content: [...(options.redactedThinking ? [{ type: "thinking", thinking: "", thinkingSignature: "encrypted-signature", redacted: true }] : []), { type: "text", text: "Hello" }], api: "openai-completions", provider: "fixture", model: "fixture", usage: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0, totalTokens: 0, cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0, total: 0 } }, stopReason: "stop", timestamp: Date.parse(created) + 1 });
	db.query("insert into message values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)").run("m1", "c1", "user", "Hi", null, "complete", null, null, null, created); db.query("insert into message values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)").run("m2", "c1", "assistant", "Hello", options.malformed ? "{" : assistant, options.partial ? "generating" : "complete", "fixture", null, null, options.collision ? created : "2025-01-01T00:00:01.000Z");
	if (options.tool) { const call = { role: "assistant", content: [{ type: "toolCall", id: "tool-1", name: "weather", arguments: {} }], api: "openai-completions", provider: "fixture", model: "fixture", usage: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0, totalTokens: 0, cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0, total: 0 } }, stopReason: "toolUse", timestamp: Date.parse(created) + 1 }; const result = { role: "toolResult", toolCallId: "tool-1", toolName: "weather", content: [{ type: "text", text: "sunny" }], isError: false, timestamp: Date.parse(created) + 2 }; db.query("update message set parts=? where id='m2'").run(JSON.stringify({ ...call, content: [...call.content, { type: "text", text: "done" }] })); db.query("insert into generation_step values (?, ?, ?)").run("m2", 0, JSON.stringify(call)); db.query("insert into generation_step values (?, ?, ?)").run("m2", 1, JSON.stringify(result)); }
	if (options.summary) db.query("insert into conversation_context_state values (?, ?)").run("c1", "old summary");
	if (options.attachment) db.query("insert into attachment values (?, ?, ?, ?, ?, ?, ?, ?, ?)").run("a1", "u1", "m1", "note.txt", "text/plain", "text", 5, "files/note.txt", created);
	if (options.multiAttachment) { db.query("insert into attachment values (?, ?, ?, ?, ?, ?, ?, ?, ?)").run("a2", "u1", "m1", "second.txt", "text/plain", "text", 6, "files/second.txt", created); db.query("insert into attachment values (?, ?, ?, ?, ?, ?, ?, ?, ?)").run("a3", "u1", "m1", "third.txt", "text/plain", "text", 5, "files/third.txt", created); }
	db.close();
	if (options.attachment) { await mkdir(join(assets, "files"), { recursive: true }); await Bun.write(join(assets, "files/note.txt"), "hello"); }
	if (options.multiAttachment) { await mkdir(join(assets, "files"), { recursive: true }); await Bun.write(join(assets, "files/second.txt"), "second"); await Bun.write(join(assets, "files/third.txt"), "third"); }
	return { root, sourceDb, sourceAssets: assets, targetDb: join(root, "v2.db"), targetAssets: join(root, "v2-assets"), reportPath: join(root, "report.json") };
}

describe("v1 to v2 migration", () => {
	test("dry runs deterministically without target state", async () => { const input = await fixture(); const first = await runMigration({ ...input, dryRun: true }); const second = await runMigration({ ...input, dryRun: true }); expect(first).toEqual(second); expect(Bun.file(input.targetDb).size).toBe(0); });
	test("migrates a clean fixture and refuses overwrite unless forced", async () => { const input = await fixture(); const report = await runMigration(input); expect(report.failures).toEqual([]); expect(report.warnings).toEqual([]); expect(Bun.file(input.targetDb).size).toBeGreaterThan(0); expect((await runMigration(input)).failures[0]!.detail).toContain("exists"); expect((await runMigration({ ...input, force: true })).failures).toEqual([]); });
	test("keeps valid tool loops and omits rolling summaries", async () => { const input = await fixture({ tool: true, summary: true }); const report = await runMigration(input); expect(report.failures).toEqual([]); expect(report.warnings.some((item) => item.code === "compaction_omitted")).toBe(true); const db = new Database(input.targetDb, { readonly: true }); expect((db.query("select count(*) as count from v2_context_compaction").get() as any).count).toBe(0); expect((db.query("select count(*) as count from v2_conversation_message").get() as any).count).toBe(4); db.close(); });
	test("rejects timestamp ties unless explicitly allowed", async () => { const input = await fixture({ collision: true }); expect((await runMigration({ ...input, dryRun: true })).failures.some((item) => item.code === "ambiguous_order")).toBe(true); const report = await runMigration({ ...input, dryRun: true, allowAmbiguousOrder: true }); expect(report.failures).toEqual([]); expect(report.warnings.some((item) => item.code === "timestamp_collision")).toBe(true); });
	test("reports malformed and partial records without canonical coercion", async () => { const malformed = await fixture({ malformed: true }); expect((await runMigration({ ...malformed, dryRun: true })).failures.some((item) => item.code === "invalid_parts_json")).toBe(true); const partial = await fixture({ partial: true }); const report = await runMigration(partial); expect(report.failures).toEqual([]); const db = new Database(partial.targetDb, { readonly: true }); expect((db.query("select status from v2_generation").get() as any).status).toBe("interrupted"); expect((db.query("select count(*) as count from v2_conversation_message").get() as any).count).toBe(1); db.close(); });
	test("copies attachment bytes and omits (rather than aborts on) a broken attachment row", async () => { const input = await fixture({ attachment: true }); expect((await runMigration(input)).failures).toEqual([]); const db = new Database(input.targetDb, { readonly: true }); expect((db.query("select count(*) as count from v2_message_attachment").get() as any).count).toBe(1); db.close();
		const sizeMismatch = await fixture({ attachment: true }); const source = new Database(sizeMismatch.sourceDb); source.query("update attachment set byteSize=6 where id='a1'").run(); source.close(); const sizeReport = await runMigration(sizeMismatch); expect(sizeReport.failures).toEqual([]); expect(sizeReport.warnings.some((item) => item.code === "attachment_omitted_size_mismatch")).toBe(true); const sizeDb = new Database(sizeMismatch.targetDb, { readonly: true }); expect((sizeDb.query("select count(*) as count from v2_attachment").get() as any).count).toBe(0); expect((sizeDb.query("select count(*) as count from v2_message_attachment").get() as any).count).toBe(0); expect((sizeDb.query("select count(*) as count from v2_conversation_message").get() as any).count).toBeGreaterThan(0); sizeDb.close();
		const missingFile = await fixture({ attachment: true }); await rm(join(missingFile.sourceAssets, "files/note.txt")); const missingReport = await runMigration(missingFile); expect(missingReport.failures).toEqual([]); expect(missingReport.warnings.some((item) => item.code === "attachment_omitted_missing_file")).toBe(true); const missingDb = new Database(missingFile.targetDb, { readonly: true }); expect((missingDb.query("select count(*) as count from v2_attachment").get() as any).count).toBe(0); missingDb.close();
	});
	test("still aborts when a storage key escapes the asset root", async () => { const input = await fixture({ attachment: true }); const source = new Database(input.sourceDb); source.query("update attachment set storageKey='../escaped.txt' where id='a1'").run(); source.close(); expect((await runMigration({ ...input, dryRun: true })).failures.some((item) => item.code === "attachment_path")).toBe(true); });
	test("migrates assistant messages with redacted (empty) thinking content", async () => { const input = await fixture({ redactedThinking: true }); const report = await runMigration(input); expect(report.failures).toEqual([]); const db = new Database(input.targetDb, { readonly: true }); const row = db.query("select messageJson from v2_conversation_message where role='assistant'").get() as any; const message = JSON.parse(row.messageJson); const thinking = message.content.find((part: any) => part.type === "thinking"); expect(thinking.thinking).toBe(""); expect(thinking.thinkingSignature).toBe("encrypted-signature"); db.close(); });
	test("assigns distinct ordinals to multiple attachments on the same message", async () => { const input = await fixture({ attachment: true, multiAttachment: true }); const report = await runMigration(input); expect(report.failures).toEqual([]); const db = new Database(input.targetDb, { readonly: true }); const bindings = db.query("select ordinal from v2_message_attachment order by ordinal").all() as any[]; expect(bindings.length).toBe(3); expect(bindings.map((b) => b.ordinal)).toEqual([0, 1, 2]); expect((db.query("select count(*) as count from v2_attachment").get() as any).count).toBe(3); db.close(); });
});
